

IF NOT EXISTS (SELECT 1 FROM dbo.Cidades WHERE ID_UF = 'SP')
BEGIN 
  -- Inserção das cidades de São Paulo
  INSERT INTO Cidades (NM_Cidades, ID_UF) VALUES
  ('Adamantina'                 , 'SP'),
  ('Adolfo'                     , 'SP'),
  ('Agudos'                     , 'SP'),
  ('Alambari'                   , 'SP'),
  ('Alfredo Marcondes'          , 'SP'),
  ('Altair'                     , 'SP'),
  ('Alumínio'                   , 'SP'),
  ('Americana'                  , 'SP'),
  ('Américo Brasiliense'        , 'SP'),
  ('Andradina'                  , 'SP'),
  ('Angatuba'                   , 'SP'),
  ('Anhembi'                    , 'SP'),
  ('Aparecida'                  , 'SP'),
  ('Araçariguama'               , 'SP'),
  ('Araçatuba'                  , 'SP'),
  ('Araraquara'                 , 'SP'),
  ('Araras'                     , 'SP'),
  ('Arco-Íris'                  , 'SP'),
  ('Arujá'                      , 'SP'),
  ('Barra Bonita'               , 'SP'),
  ('Barretos'                   , 'SP'),
  ('Barrinha'                   , 'SP'),
  ('Bastos'                     , 'SP'),
  ('Bauru'                      , 'SP'),
  ('Bebedouro'                  , 'SP'),
  ('Bento de Abreu'             , 'SP'),
  ('Bernardino de Campos'       , 'SP'),
  ('Bertioga'                   , 'SP'),
  ('Bilac'                      , 'SP'),
  ('Birigui'                    , 'SP'),
  ('Boituva'                    , 'SP'),
  ('Bom Jesus dos Perdões'      , 'SP'),
  ('Boracéia'                   , 'SP'),
  ('Borá'                       , 'SP'),
  ('Botucatu'                   , 'SP'),
  ('Bragança Paulista'          , 'SP'),
  ('Brailândia Paulista'        , 'SP'),
  ('Campinas'                   , 'SP'),
  ('Campo Limpo Paulista'       , 'SP'),
  ('Campo Grande'               , 'SP'),
  ('Cananéia'                   , 'SP'),
  ('Capão Bonito'               , 'SP'),
  ('Capela do Alto'             , 'SP'),
  ('Caraguatatuba'              , 'SP'),
  ('Carapicuíba'                , 'SP'),
  ('Cardoso Pimentel'           , 'SP'),
  ('Casa Branca'                , 'SP'),
  ('Casimiro de Abreu'          , 'SP'),
  ('Catalão'                    , 'SP'),
  ('Catanduva'                  , 'SP'),
  ('Cotia'                      , 'SP'),
  ('Cravinhos'                  , 'SP'),
  ('Cristais Paulista'          , 'SP'),
  ('Cubatão'                    , 'SP'),
  ('Cunha'                      , 'SP'),
  ('Descalvado'                 , 'SP'),
  ('Diadema'                    , 'SP'),
  ('Divinolândia'               , 'SP'),
  ('Dolcinópolis'               , 'SP'),
  ('Dourado'                    , 'SP'),
  ('Dracena'                    , 'SP'),
  ('Echaporã'                   , 'SP'),
  ('Eldorado'                   , 'SP'),
  ('Elias Fausto'               , 'SP'),
  ('Embu das Artes'             , 'SP'),
  ('Embu-Guaçu'                 , 'SP'),
  ('Emília'                     , 'SP'),
  ('Engenheiro Coelho'          , 'SP'),
  ('Esmeralda'                  , 'SP'),
  ('Estiva Gerbi'               , 'SP'),
  ('Fernandópolis'              , 'SP'),
  ('Fernão'                     , 'SP'),
  ('Ferraz de Vasconcelos'      , 'SP'),
  ('Floreal'                    , 'SP'),
  ('Flórida Paulista'           , 'SP'),
  ('Francisco Morato'           , 'SP'),
  ('Franca'                     , 'SP'),
  ('Francisco Alves'            , 'SP'),
  ('Gabriel Monteiro'           , 'SP'),
  ('Gália'                      , 'SP'),
  ('Garça'                      , 'SP'),
  ('Gavião Peixoto'             , 'SP'),
  ('General Salgado'            , 'SP'),
  ('Getulina'                   , 'SP'),
  ('Glicério'                   , 'SP'),
  ('Guaraci'                    , 'SP'),
  ('Guaraçaí'                   , 'SP'),
  ('Guarujá'                    , 'SP'),
  ('Guarulhos'                  , 'SP'),
  ('Iacanga'                    , 'SP'),
  ('Ibiúna'                     , 'SP'),
  ('Icém'                       , 'SP'),
  ('Igaratá'                    , 'SP'),
  ('Igarapava'                  , 'SP'),
  ('Iguape'                     , 'SP'),
  ('Ilhabela'                   , 'SP'),
  ('Indaiatuba'                 , 'SP'),
  ('Ipauçu'                     , 'SP'),
  ('Iperó'                      , 'SP'),
  ('Ipeúna'                     , 'SP'),
  ('Ipuã'                       , 'SP'),
  ('Iracemápolis'               , 'SP'),
  ('Irapuã'                     , 'SP'),
  ('Irara'                      , 'SP'),
  ('Itatiba'                    , 'SP'),
  ('Itápolis'                   , 'SP'),
  ('Itapevi'                    , 'SP'),
  ('Itapecerica da Serra'       , 'SP'),
  ('Itapetininga'               , 'SP'),
  ('Itapeva'                    , 'SP'),
  ('Itatiaia'                   , 'SP'),
  ('Itirapina'                  , 'SP'),
  ('Itu'                        , 'SP'),
  ('Jaboticabal'                , 'SP'),
  ('Jacareí'                    , 'SP'),
  ('Jaguariúna'                 , 'SP'),
  ('Jales'                      , 'SP'),
  ('Jandira'                    , 'SP'),
  ('Jarinu'                     , 'SP'),
  ('Jaú'                        , 'SP'),
  ('Joanópolis'                 , 'SP'),
  ('Jundiaí'                    , 'SP'),
  ('Juquiá'                     , 'SP'),
  ('Juventude'                  , 'SP'),
  ('Lagoinha'                   , 'SP'),
  ('Laranjal Paulista'          , 'SP'),
  ('Lavrinhas'                  , 'SP'),
  ('Limeira'                    , 'SP'),
  ('Lindóia'                    , 'SP'),
  ('Lourdes'                    , 'SP'),
  ('Lucélia'                    , 'SP'),
  ('Luís Antonio'               , 'SP'),
  ('Macaubal'                   , 'SP'),
  ('Mauá'                       , 'SP'),
  ('Mendonça'                   , 'SP'),
  ('Meridiano'                  , 'SP'),
  ('Mesópolis'                  , 'SP'),
  ('Mogi das Cruzes'            , 'SP'),
  ('Mogi Mirim'                 , 'SP'),
  ('Mombuca'                    , 'SP'),
  ('Monte Alto'                 , 'SP'),
  ('Monte Mor'                  , 'SP'),
  ('Monte Verde'                , 'SP'),
  ('Morro Agudo'                , 'SP'),
  ('Morro do Chapéu'            , 'SP'),
  ('Natividade da Serra'        , 'SP'),
  ('Nazareth'                   , 'SP'),
  ('Neves Paulista'             , 'SP'),
  ('Nhandeara'                  , 'SP'),
  ('Nipoã'                      , 'SP'),
  ('Nogueira'                   , 'SP'),
  ('Olímpia'                    , 'SP'),
  ('Osasco'                     , 'SP'),
  ('Ourinhos'                   , 'SP'),
  ('Pacaembu'                   , 'SP'),
  ('Palestina'                  , 'SP'),
  ('Palmeira d’Oeste'           , 'SP'),
  ('Pardinho'                   , 'SP'),
  ('Pariquera-Açu'              , 'SP'),
  ('Parnaíba'                   , 'SP'),
  ('Parque Três Marias'         , 'SP'),
  ('Paulínia'                   , 'SP'),
  ('Pedro de Toledo'            , 'SP'),
  ('Pereira Barreto'            , 'SP'),
  ('Piedade'                    , 'SP'),
  ('Pilar do Sul'               , 'SP'),
  ('Piracaia'                   , 'SP'),
  ('Piracicaba'                 , 'SP'),
  ('Pirassununga'               , 'SP'),
  ('Planalto'                   , 'SP'),
  ('Pontal'                     , 'SP'),
  ('Porteira Preta'             , 'SP'),
  ('Porto Ferreira'             , 'SP'),
  ('Potim'                      , 'SP'),
  ('Pratânia'                   , 'SP'),
  ('Presidente Epitácio'        , 'SP'),
  ('Presidente Prudente'        , 'SP'),
  ('Quatá'                      , 'SP'),
  ('Queiroz'                    , 'SP'),
  ('Rafard'                     , 'SP'),
  ('Rancharia'                  , 'SP'),
  ('Regente Feijó'              , 'SP'),
  ('Registro'                   , 'SP'),
  ('Ribeirão Bonito'            , 'SP'),
  ('Ribeirão Preto'             , 'SP'),
  ('Rincão'                     , 'SP'),
  ('Rio Claro'                  , 'SP'),
  ('Rio das Pedras'             , 'SP'),
  ('Rio Grande da Serra'        , 'SP'),
  ('Riversul'                   , 'SP'),
  ('Rochedo'                    , 'SP'),
  ('Rodolfo Fernandes'          , 'SP'),
  ('Rubiataba'                  , 'SP'),
  ('Salto'                      , 'SP'),
  ('Salto de Pirapora'          , 'SP'),
  ('Salto Grande'               , 'SP'),
  ('Santa Adélia'               , 'SP'),
  ('Santa Bárbara d’Oeste'      , 'SP'),
  ('Santa Branca'               , 'SP'),
  ('Santa Clara d’Oeste'        , 'SP'),
  ('Santa Cruz das Palmeiras'   , 'SP'),
  ('Santa Fé do Sul'            , 'SP'),
  ('Santa Rita do Passa Quatro' , 'SP'),
  ('Santa Rosa de Viterbo'      , 'SP'),
  ('Santo André'                , 'SP'),
  ('Santo Antônio do Jardim'    , 'SP'),
  ('Santo Antônio do Pinhal'    , 'SP'),
  ('Santos'                     , 'SP'),
  ('São Bento do Sapucaí'       , 'SP'),
  ('São Bernardo do Campo'      , 'SP'),
  ('São Caetano do Sul'         , 'SP'),
  ('São Carlos'                 , 'SP'),
  ('São João da Boa Vista'      , 'SP'),
  ('São João de Iracema'        , 'SP'),
  ('São José do Barreiro'       , 'SP'),
  ('São José do Rio Pardo'      , 'SP'),
  ('São José dos Campos'        , 'SP'),
  ('São Manuel'                 , 'SP'),
  ('São Miguel Paulista'        , 'SP'),
  ('São Paulo'                  , 'SP'),
  ('São Pedro'                  , 'SP'),
  ('São Sebastião'              , 'SP'),
  ('São Simão'                  , 'SP'),
  ('Sorocaba'                   , 'SP'),
  ('Tatuí'                      , 'SP'),
  ('Taubaté'                    , 'SP'),
  ('Teodoro Sampaio'            , 'SP'),
  ('Templo de Salomão'          , 'SP'),
  ('Torrinha'                   , 'SP'),
  ('Tremembé'                   , 'SP'),
  ('Tubarão'                    , 'SP'),
  ('Valinhos'                   , 'SP'),
  ('Valparaíso'                 , 'SP'),
  ('Vargem Grande Paulista'     , 'SP'),
  ('Várzea Paulista'            , 'SP'),
  ('Venceslau Brás'             , 'SP'),
  ('Votorantim'                 , 'SP'),
  ('Votuporanga'                , 'SP');
END

